name: Build and Deploy React App to GitHub Pages

on:
  push:
    branches:
      - "feature"  # Trigger on push to the 'feature' branch
  workflow_dispatch:  # Allows manual trigger from the Actions tab

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job for React app
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Check out the repository code

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Set up Node.js
        with:
          node-version: '20.5.0'  # Your Node.js version

      - name: Install dependencies
        run: npm install  # Install project dependencies

      - name: Build the React app
        run: npm run build  # Build the app, output will be in 'build/' folder

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3  # Upload the build artifacts
        with:
          path: './build'  # Path to the build directory where React output is stored

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4  # Deploy to GitHub Pages
